### ISSUE TITLE
Fix syntax highlighting

### ISSUE THREAD

**Issue by welpo** [welpo/tabi#1]
Add Syntax Highlighting following the steps from: 
[https://www.getzola.org/documentation/content/syntax-highlighting/](https://www.getzola.org/documentation/content/syntax-highlighting/)

The goal is to make it look something like: 
![Image](https://i.imgur.com/RhSNKTO.png)
Image Source: https://pawroman.github.io/zola-theme-terminimal/welcome-terminimal-theme/

**Comment by serginogal** [comment]
The syntax highlight should be fixed with the the following Pull Request: https://github.com/welpo/tabi/pull/2
