### ISSUE TITLE
Low contrast on backticked words inside links when hovered

### ISSUE THREAD

**Issue by SeaDve** [welpo/tabi#106]
# Bug Report

First of all, thanks for the theme! It works really well

## Environment

Zola version: 0.17.2
tabi commit: 4952ce88

## Expected Behavior
Good contrast on backticked words inside links when hovered

## Current Behavior
Low contrast on backticked words inside links when hovered

![image](https://github.com/welpo/tabi/assets/64297935/969e91c7-2fd6-4883-b59e-d87c07f8f942)

![image](https://github.com/welpo/tabi/assets/64297935/976e8a56-b736-42fe-b547-9a7a73dd8b28)

## Step to reproduce
1. Create a link with backticked word inside. For example:

```md
[some `backticked word`](https://www.google.com/)
```

2. Hover the created link
3. Observe the low contrast on the backticked word

**Comment by welpo** [comment]
Hi there,

Thank you for bringing this issue to my attention and for the detailed bug report!

I've identified the cause of the low contrast on backticked words inside links when hovered and implemented a fix.

The solution was to make the `code` background color inherit the same background as the hovered link:

https://github.com/welpo/tabi/blob/f8891dba2cc0d1a8619bf9b01bb06e4c7560b7ec/sass/parts/_code.scss#L40-L42

With this change, the contrast for backticked words inside hovered links will be the same as for normal text. Here's what it looks like:

![fix](https://github.com/welpo/tabi/assets/6399341/3bc484f6-c50c-4e2a-8113-80f357d05caa)

Please pull the latest changes and check it on your end. Let me know if it works for you or if there are any other concerns!

Thank you for using tabi and for bringing this to my attention. Feedback like yours is invaluable for continuous improvement.

**Comment by SeaDve** [comment]
I appreciate the quick fix and detailed response. Pulling the latest changes certainly fixes the issue. Thanks, again!
