### ISSUE TITLE
Can't have no favicon

### ISSUE THREAD

**Issue by stevenroose** [welpo/tabi#125]
Similar to https://github.com/welpo/tabi/issues/122. It seems that when no favicon or favicon_emoji is specified, the tabi favicon is used. It should be possible to not have a favicon, right?

**Comment by welpo** [comment]
Thanks for reporting this, Steven.

Of course, it should be possible to not have a favicon.

I recently learnt that when a variable is unset in `config.toml` but set in a theme's `theme.toml`, this second value will be used—that's the reason behind this issue.

Until now, I've kept in sync the `config.toml` for tabi and its `theme.toml`, but now I see it makes sense to comment out certain variables (like email or favicon) from `theme.toml`.

I will modify `theme.toml` to have saner defaults (like removing the email field) and modify [the pre-commit hook](https://github.com/welpo/tabi/blob/main/.githooks/pre-commit) to not sync them, but instead check for the number of lines on each `[extra]` section, for example.

**Comment by stevenroose** [comment]
I actually didn't try `favicon_emoji = ""`.. Would that work?

**Comment by stevenroose** [comment]
That actually seems to work for me..

**Comment by welpo** [comment]
That does work, because an empty string evaluates to `false`.

I'll still make the changes I mentioned; I belive a missing/commented out `favicon` value (or even worse, `email`) should not render an email or a favicon.

**Comment by welpo** [comment]
Done in #127.
