### ISSUE TITLE
Use `<h1>` tags for titles

### ISSUE THREAD

**Issue by donovanglover** [welpo/tabi#133]
# Feature Request

## Summary
Currently tabi doesn't use any `<h1>` tags on pages outside of the cards template.

## Motivation
At least one `<h1>` on each page is useful for accessibility.

## Detailed Description
- Change `.article-title` from `<div>` to `<h1>`.
- Use `<h1>` for other titles like `.section-title` and `#home-banner-header`

## Additional Context
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements

**Comment by welpo** [comment]
Thanks for such a thorough report! It saved me some time :)

I fixed this in #140.
