### ISSUE TITLE
Missing title on `/tags`

### ISSUE THREAD

**Issue by donovanglover** [welpo/tabi#134]
# Bug Report

## Environment

Zola version: 0.17.2
tabi commit: https://github.com/welpo/tabi/commit/c79407e6d7ea544a8b337e372309909a58640423

## Expected Behavior
Title should be "Tags" or "All tags" when navigating to `/tags`

## Current Behavior
`/tags` doesn't have a unique title

## Step to reproduce
Navigate to https://welpo.github.io/tabi/tags/

**Comment by welpo** [comment]
Thanks for reporting this, Donovan.

I'm working on a PR which will overhaul the translation/i18n of the theme. That PR will fix this issue.
