### ISSUE TITLE
Option to have page title before site title in `<title>`

### ISSUE THREAD

**Issue by donovanglover** [welpo/tabi#135]
# Feature Request

## Summary
Having the page title before the site title is useful when the site title is long and prevents users from seeing the page title in tabs.

## Motivation
An option lets users with short titles keep their site title as the most important factor.

## Detailed Description
Should be easy to adjust `set_title.html` and swap prefix/suffix based on a config value.

**Comment by welpo** [comment]
Good idea! I'm on it.

Thanks for these resports!
