### ISSUE TITLE
Add support for page-specific styles

### ISSUE THREAD

**Issue by donovanglover** [welpo/tabi#138]
# Feature Request

## Summary
Page slugs as classes in the HTML would let users use per-page CSS.

Alternatively, [this stackoverflow answer](https://stackoverflow.com/questions/45727055/is-there-a-css-selector-that-applies-when-matching-specific-values-in-the-url/71489762#71489762) seems like a more modern solution that's easier to implement.

## Motivation
AFAIR, used by WordPress themes and similar tools to let users style specific pages.

## Detailed Description
Include an additional class that lets users style pages based on the slug. Example:

- `/blog/` -> `page-blog`
- `/blog/a-specific-post/` -> `page-blog-a-specific-post`

Alternatively, add an HTML data-* attribute with the URL and query it with CSS.

## Additional Context
I'd personally use this to make an about page look more like an about page and less like a blog post.

- Should there be another template that's better suited for pages where the date isn't relevant?
- Should removing the [`.meta`](https://github.com/welpo/tabi/blob/c79407e6d7ea544a8b337e372309909a58640423/templates/macros/content.html#L56) from a page be an option?

The other use case I can see is telling which link is active in the navigation, although this may be possible to implement in [`nav.html`](https://github.com/welpo/tabi/blob/c79407e6d7ea544a8b337e372309909a58640423/templates/partials/nav.html#L14) directly.

**Comment by welpo** [comment]
I think it would make sense to add another template to handle non-posts. For example, an "About Me" page, a Privacy Policy, etc.

Ideas:
- uses the full width of the page (unlike articles), looking very close to the current demo's homepage, but with a normal header/title
- no metadata (time read, publication time, etc)
- sans serif, or serif font? I think I'm leaning towards sans serif, as serif is only used in article paragraphs right now.

**Comment by xvello** [comment]
:+1: for a non-post page template. an `About me` page should be pretty easy to achieve by creating a custom template extending `base.html`, but having it turn-key would be a plus.

For page-specific styles, the theme already supports a `page.extra.stylesheets` param, which should be enough for this use case. For simpler deploys with sass disabled, [commonmark allows specifying an inline <style> block](https://spec.commonmark.org/0.30/#html-blocks), but these are blocked by the CSP your theme defines, so it's not an option.

**Comment by welpo** [comment]
> For simpler deploys with sass disabled, [commonmark allows specifying an inline <style> block](https://spec.commonmark.org/0.30/#html-blocks), but these are blocked by the CSP your theme defines, so it's not an option

Two points:

1. `page.extra.stylesheets` is able to load regular CSS files as well, even with SASS disabled.

2. Regarding the inline style blocks being disabled, the default can be modified to allow them

```toml
allowed_domains = [
    { directive = "style-src", domains = ["'self'", "'unsafe-inline'"] },
# Other directives.
]
```

In any case, I'll create the template soon.

**Comment by donovanglover** [comment]
Thanks! Will close this issue since the main question I had was solved

**Comment by welpo** [comment]
The not-an-article template (`info-page.html`) has been added in #147. You can see it [live on the demo](https://welpo.github.io/tabi/about/).

Hope you like it!

**Comment by donovanglover** [comment]
It looks great, thanks!
