### ISSUE TITLE
Live reload with Content Security Policy

### ISSUE THREAD

**Issue by donovanglover** [welpo/tabi#139]
# Bug Report

## Environment

Zola version: 0.17.2
tabi commit: https://github.com/welpo/tabi/commit/c79407e6d7ea544a8b337e372309909a58640423

## Expected Behavior
Live reload should work

## Current Behavior
Live reload doesn't work due to the Content Security Policy

## How to Fix
I fixed this by adding `connect-src 'self' ws:;` to [`header.html`](https://github.com/welpo/tabi/blob/c79407e6d7ea544a8b337e372309909a58640423/templates/partials/header.html#L89). AFAIR, there should be a variable to determine if zola is running in `serve` mode.

**Comment by welpo** [comment]
I was aware of this issue and indeed looked for a Zola variable that would let me know whether it was serving or building, but I couldn't find it.

I thought I could create an `[extra]` variable in `config.toml` for this, but it'd be too cumbersome. I'll check again if there's a way to tell whether Zola is in `serve` mode.

Thanks for your report!

**Comment by welpo** [comment]
Apparently I didn't look hard enough last time.

We can check `config.mode` to see whether it's Zola is in `build`, `serve` or `check` mode.

Sources:
https://github.com/getzola/zola/issues/1646
https://www.getzola.org/documentation/templates/overview/

**Comment by welpo** [comment]
Should be fixed with #144!
