### ISSUE TITLE
og:title should be title of page

### ISSUE THREAD

**Issue by donovanglover** [welpo/tabi#148]
# Bug Report

## Environment

Zola version: 0.17.2
tabi commit: https://github.com/welpo/tabi/commit/f1d92a73ce18060d38aebf91b8fd3d18914d0e73

## Expected Behavior
`og:title` should be the title of the page so things like Firefox Reader view work as expected.

https://ogp.me/

## Current Behavior
`og:title` is the site title

## Step to reproduce
https://github.com/welpo/tabi/blob/f1d92a73ce18060d38aebf91b8fd3d18914d0e73/templates/partials/header.html#L82

**Comment by welpo** [comment]
Thanks for reporting this, Donovan.

I'll take a look at the SEO-related lines to fix this and see if anything else can be improved.
