### ISSUE TITLE
Missing image links for project pages

### ISSUE THREAD

**Issue by donovanglover** [welpo/tabi#152]
# Bug Report

## Environment

Zola version: 0.17.2
tabi commit: https://github.com/welpo/tabi/commit/f1d92a73ce18060d38aebf91b8fd3d18914d0e73

## Expected Behavior
Images should be clickable for project pages.

## Current Behavior
Images are only clickable if `page.extra.link_to` is used.

## Step to reproduce
https://github.com/welpo/tabi/blob/f1d92a73ce18060d38aebf91b8fd3d18914d0e73/templates/partials/cards_pages.html#L12-L14

**Comment by welpo** [comment]
Where would the image lead to, if there's no external URL? To the pages that are built for each project?

**Comment by donovanglover** [comment]
`page.permalink` would be ideal since they get [auto-generated](https://osc.garden/projects/tabi/).

**Comment by welpo** [comment]
Makes sense. I always thought of the auto-generated pages as a nuisance, but I guess they could be used as a post to explain the project (with the default article template or with the new `info-page.html`).

On it!

**Comment by donovanglover** [comment]
There could be optional icons or text below the project name such as GitHub, Demo Website, etc.

This would replace `link_to`.

**Comment by welpo** [comment]
> There could be optional icons or text below the project name such as GitHub, Demo Website, etc.

On the project's `.md` file, you mean, right? (i.e. the example you linked from my site)

**Comment by donovanglover** [comment]
I think the project page is better than the listing to avoid giving the user too many choices. This also drives traffic to the project pages.

**Comment by welpo** [comment]
Done in #157!

**Comment by donovanglover** [comment]
Thanks!
