### ISSUE TITLE
Issue with CORS headers / CSP policy for static content.

### ISSUE THREAD

**Issue by sandman** [welpo/tabi#155]
Hi,
I have deployed my lightly modified Tabi-theme site on Github Pages: https://sandip.live/
Unfortunately, the images, CSS and other static assets are not loaded:
![image](https://github.com/welpo/tabi/assets/11884/29d9645d-52ba-494e-ba47-a10a06b74fea)

What am I doing wrong?

**Comment by donovanglover** [comment]
Change `base_url` in `config.toml` to https://sandip.live

**Comment by sandman** [comment]
Thanks @donovanglover - that worked! 
A related question: How should the static images be referenced in deployment? I have my images under /static/img and these seem to be copied into /public/img. However, the following image Markdowns both throw a 404:

`![Hair on Fire problem](/public/img/hair-fire.jpg "Find customers with a burning problem")*Your customer with a hair on fire problem*`
`![Hair on Fire problem](/static/img/hair-fire.jpg "Find customers with a burning problem")*Your customer with a hair on fire problem*`

**Comment by donovanglover** [comment]
The contents of public end up as your website root, so you'd use `/img/hair-fire.jpg`

**Comment by sandman** [comment]
Thanks so much @donovanglover ! You've been very helpful :+1:
