### ISSUE TITLE
Add ability to include page.content on atom.xml

### ISSUE THREAD

**Issue by SeaDve** [welpo/tabi#160]
# Feature Request

## Summary
Add the ability to include `page.content` on `atom.xml` since currently, it is empty when put into an RSS reader

## Motivation
It only shows the description without the `<content>` tag. This would benefit the user as it will actually show the actual content of the blog in the RSS reader.

## Detailed Description
Either simply append:

```html
<content type="html">{{ page.content | safe }}</content>
```

on `atom.xml`

or

add an option to opt-in to that

**Comment by welpo** [comment]
On it!
