### ISSUE TITLE
Allow relative paths on extra.social_media_card

### ISSUE THREAD

**Issue by SeaDve** [welpo/tabi#161]
# Feature Request

## Summary
Basically, it should work as expected when the path on `extra.social_meda_card` is relative to the current path.

## Motivation
It makes it easier for the user to include images without having to put it on `static/img/` or other paths; the user can simply put it together with files on `blog/some-blog/`.

## Detailed Description
I think this could be implemented by allowing both relative and absolute paths.

**Comment by welpo** [comment]
I expected `get_url` to handle that case, but it doesn't. Creating a PR now.

**Comment by SeaDve** [comment]
That was quick, thank you!
