### ISSUE TITLE
Add template for a custom page on root

### ISSUE THREAD

**Issue by SeaDve** [welpo/tabi#162]
# Feature Request

## Summary
Add a template for a custom page on the root. 

## Motivation
For example, when a user may want to add an about page, they can simply use the template `X.html`, instead of modifying the theme.

## Detailed Description
I currently use a custom template to get around this, and it is implemented like the following:

```html
{% extends "base.html" %}

{% block main_content %}
    {{ macros_page_header::page_header(title=section.title) }}

    <br>

    {{ section.content | safe }}
{% endblock main_content %}
```

**Comment by welpo** [comment]
I'm not sure I understand the request.

I recently added (PR #147) an `info-page.html` template, which looks like [this](https://welpo.github.io/tabi/about/). It's set up like this: https://github.com/welpo/tabi/blob/049babbd97555b2f32c611948e0ebe66a021b7d0/content/pages/about.md?plain=1#L1-L4

Notice how I'm specifying an absolute path as well as the template.

Is this what you were requesting? If not, please clarify.

Thanks!

**Comment by SeaDve** [comment]
Oh, last time I checked it wasn't there. That's exactly what I was looking for. Closing this. Thankss!
