### ISSUE TITLE
SEO and commenting plugins

### ISSUE THREAD

**Issue by sandman** [welpo/tabi#171]
Does Tabi provide capabilities for 1) SEO/web analytics and 2) commenting on blog posts?

**Comment by welpo** [comment]
tabi supports comments with 4 different systems: giscus (GitHub based), utterances (GitHub based), Hyvor Talk (paid) and Isso (self hosted). See the docs: https://welpo.github.io/tabi/blog/comments/

Regarding analytics, there's no such feature. If you find a system which is privacy-respecting (i.e. not Google Analytics), I'd consider adding support to it.
