### ISSUE TITLE
Optimizing Fonts

### ISSUE THREAD

**Issue by donovanglover** [welpo/tabi#174]
# Feature Request

## Summary
I noticed that fonts total to 822 KB when loading a blog post, which is about 3/4 the size of a page.

The fonts on [google-webfonts-helper](https://gwfh.mranftl.com/fonts) are generally smaller, so I assume some optimization can be done to significantly reduce the file sizes.

## Motivation
Faster load times. Only load what's used.

## Detailed Description
- How many font weights are needed?
- What charsets are used?

## Additional Context
Should users be able to customize the fonts used? Specifying fonts can be useful especially if system fonts are preferred.

**Comment by donovanglover** [comment]
I noticed that tabi takes advantage of the modern [variable fonts](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#variable_fonts) feature in CSS, so it may be difficult to use non-variable fonts like the 400/600/700 ones.

I also saw the font charsets with [FontForge](https://github.com/fontforge/fontforge). Overall, I think optimizations can be done on a case-by-case basis and feel like the current fonts are already good for a majority of users.

**Comment by welpo** [comment]
I'm interested in reducing the size of the resources, so I'll definitely look into some options in regards to fonts.

**Comment by donovanglover** [comment]
The `google-webfonts-helper` link above is pretty good when it comes to font sizes. The biggest downside is that existing `font-weight`s would have to be rounded to the nearest 100.

Potential advantages include more consistent fonts across a variety of browsers. [qutebrowser](https://qutebrowser.org/) has trouble showing some of the font sizes, for example.

**Comment by welpo** [comment]
## Coding Font

For the mono/code font (Cascadia Code), I've ran:

```bash
pyftsubset CascadiaCode-SemiLight.woff2 \
  --layout-features="*" \
  --desubroutinize \
  --unicodes=U+0020-007E \
  --flavor=woff2 \
  --output-file=font.woff2
```

This compresses the font file from 133KB to 25KB. The font includes:

- Basic ASCII characters (`U+0020-007E`): Covers English and most coding symbols.
- Ligatures: As layout features are preserved (`--layout-features="*"`), ligatures commonly used in coding are retained.

I believe this subset should be sufficient for code formatting in the vast majority of use-cases, satisfying 99.9% of users.

---

## Serif & Sans Serif

For the serif and sans-serif fonts, I've ran:

```bash
pyftsubset SourceSerif4Variable-Roman.otf.woff2 \
  --layout-features="" \
  --desubroutinize \
  --unicodes="U+0020-00FF,U+0100-024F,U+1E00-1EFF,\
              U+0400-052F,U+0391-03D6,\
              U+4E00-9FFF,U+3400-4DBF,U+20000-2A6DF,\
              U+3040-309F,U+30A0-30FF,\
              U+0600-06FF,U+2000-206F,U+2190-21FF" \
  --flavor=woff2 \
  --output-file=optimized_font.woff2
```

This subset includes:

- Latin and Latin Extended (`U+0020-00FF, U+0100-024F, U+1E00-1EFF`): Covers most European languages including those with diacritics and accents.
- Cyrillic (`U+0400-052F`): Covers languages like Russian and Ukrainian.
- Greek (`U+0391-03D6`): Includes basic Greek characters.
- Chinese (`U+4E00-9FFF, U+3400-4DBF, U+20000-2A6DF`): A broad set for Simplified and Traditional Chinese.
- Japanese (`U+3040-309F, U+30A0-30FF`): Includes Hiragana and Katakana.
- Arabic (`U+0600-06FF`): Basic Arabic script.
- General Punctuation (`U+2000-206F`): Covers a range of punctuation marks including the bullet point, dashes, and various kinds of spaces.

This configuration should cover a broad spectrum of languages and scripts, aiming to satisfy most use-cases.

This brings the sans serif font, Inter-4.0-beta9h, from 326KB to 191KB. (Kept layout-features)

The serif font, Source Serif 4, went from to 429KB to 196KB. (Removed layout-features; saw no downside)

Aggregated, this takes the font sizes f rom 888KB to 412; less than half of the original size.

---

I will be doing a PR with these changes soon.

**Comment by donovanglover** [comment]
That sounds awesome! Thanks for working on this!

**Comment by welpo** [comment]
Done! 

Thanks for requesting this, I had been meaning to look into it.

PR: #186. You might be interested in the last section, which includes instructions to create your own—potentially much smaller— subsets without needing to modify the theme's files.
