### ISSUE TITLE
Image support for posts on listing pages

### ISSUE THREAD

**Issue by donovanglover** [welpo/tabi#181]
# Feature Request

## Summary
Would be cool if post images were shown on e.g. tag pages.

## Motivation
Image-centric blogs & posts

## Detailed Description
Images could be shown where the date is on e.g. https://welpo.github.io/tabi/tags/markdown/

## Additional Context
Should `extra.local_image` be used or another variable?

**Comment by welpo** [comment]
What would happen when the browser is not desktop-sized (i.e. when the date moves over the post title)?

It shouldn't be too hard to do, but I'm not sure it's going to look good. Regarding the variable name, maybe `post_thumbnail`?

Would you like to work on this?

**Comment by donovanglover** [comment]
Sure! I haven't thought much about how it'd look, but I'll see what I can do.

**Comment by welpo** [comment]
Fantastic! Feel free to share any progress so we can discuss this.
