### ISSUE TITLE
Means of including legal documents in the footer

### ISSUE THREAD

**Issue by Almost-Senseless-Coder** [welpo/tabi#191]
# Feature Request

## Summary

Modern blogs often need to link to legal documents such as an imprint, privacy policy or terms of service. Integrating this via Tabi (similar to the socials section) would be helpful.

## Motivation

Tabi doesn't offer a means of including legal documents - like a privacy policy - in the footer of a website, except if the user manually creates their own footer template.

## Detailed Description

Currently, users who wish to add extra content to the footer have to create their own variant of `templates/partials/footer.html`. This makes updating Tabi more challenging, as changes within Tabi would need to get integrated into that footer partial manually.

Additionally, for blind users it may be hard to judge whether their integration of legal documents is visually sound - which is particularly critical as many jurisdictions demand these documents are well visible and easy to locate.

Of course, the documents could get added to the menu at the top, but that would be unusual - typically, legal documents are linked in the footer.

The implementation could occur similar to that of the menu or social icons area, with support for i18n akin to the menu.

**Comment by welpo** [comment]
Great suggestion. Working on it!
