### ISSUE TITLE
Hyvortalk doesn't display in certain conditions

### ISSUE THREAD

**Issue by nyadiia** [welpo/tabi#194]
# Bug Report

## Environment

Zola version: 0.17.2
tabi commit: 228f1ea6e51cf75bb1a44db7aa94cd634802e177

## Expected Behavior
Hyvortalk should display at the bottom in it's normal place

## Current Behavior
When `comments` is in any header, hyvortalk doesn't display. Unknown whether this happens with other comments systems.

## Step to Reproduce
1. create a post with `comments` in the header
2. enable hyvortalk on post or globally
3. scroll to bottom

**Comment by welpo** [comment]
Nice! Good job figuring out the issue. Fixing it now.
