### ISSUE TITLE
Example website images leak into generated output

### ISSUE THREAD

**Issue by xvello** [welpo/tabi#199]
# Bug Report

Thanks for this great theme! I'm using it for https://xvello.net/

While deploying my website, I was surprised by the size of the generated output, and it turns out that a lot of unnecessary images are copied over:

## Environment

Zola version: 0.17.2
tabi commit: c0a07cb

## Expected Behavior

Only required static assets are copied to the generated website.

## Current Behavior

`public/img/` contains 6MiB of images from the example content. Co-locating these images in the `contents/` folder would avoid this.

## Step to Reproduce

```bash
zola init
git clone https://github.com/welpo/tabi.git themes/tabi
cat <<EOF > config.toml
base_url = "https://example.com"
theme = "tabi"
title = "Your Site Title"
EOF
cat <<EOF > content/_index.md
+++
title = "Home"
paginate_by = 5 # Set the number of posts per page
template = "index.html"
+++
EOF
zola build

du -hs public/img/
6,2M    public/img/
```

**Comment by welpo** [comment]
Thanks for reporting this, Xavier! I had not noticed this issue, but it's an important one.

I'll start working on a fix.

**Comment by welpo** [comment]
Done! #200

**Comment by xvello** [comment]
Thanks a lot Óscar! :bow:

**Comment by welpo** [comment]
Thank you for reporting it and using tabi!
