### ISSUE TITLE
list_posts should show draft status

### ISSUE THREAD

**Issue by xvello** [welpo/tabi#202]
Hello! When running with `--drafts`, I like that the draft status is reflected on the post itself, but I'd love to have it show in the post list too. Here's a quick mockup:

![image](https://github.com/welpo/tabi/assets/6241083/256334f8-7618-42fc-943f-9e5a8a5fd5c3)

Alternatively, we could show the draft label at the start of the tag list, but it might get too noisy there.

Happy to open a PR to implement it if you're OK with the feature and the mockup.

**Comment by welpo** [comment]
I like it! Happy to accept a PR for this change. I like the position in the screenshot, too.
