### ISSUE TITLE
Is it possible to center-align text?

### ISSUE THREAD

**Issue by kendofriendo** [welpo/tabi#228]
Sorry if this is a stupid question. I want to align specific headers on an about page. I tried using html like in regular markdown but it didn't work.

**Comment by welpo** [comment]
> Sorry if this is a stupid question

No such thing!

If I understand your goal correctly, you want something like [this](https://osc.garden/projects/chu/):

![](https://github.com/welpo/tabi/assets/6399341/fee3f77a-07fd-4daf-990a-a642f0ace41c)

where the View on Github header is centered.

If so, this is how I achieved it:

```md
#### [View on GitHub](https://github.com/welpo/chu) {.centered-text}
```

The last part adds the class `centered-text`, which is as simple as:

```cs
.centered-text {
    text-align: center;
}
```

Hope that helps!

**Comment by kendofriendo** [comment]
awesome that did it! thank you! and thank you for the great theme!
