### ISSUE TITLE
Default taxonomies

### ISSUE THREAD

**Issue by arichtman** [welpo/tabi#229]
# Feature Request

## Summary

Zola can do unlimited taxonomies, provided there is a fallback template.
I would like to request such a feature.

## Motivation

Multiple taxonomies allows applying more granular metadata and more ways to "slice" up the site's content.

## Detailed Description

I think all we need is to add `taxonomy_single.html` and `taxonomy_list.html` to the `templates` directory.
I suspect it would be much the same content of the `tags` taxonomy templates.

## Additional Context

https://www.getzola.org/documentation/templates/taxonomies/

**Comment by welpo** [comment]
Thanks for requesting this and sharing the docs.

I'll look into it soon.

**Comment by welpo** [comment]
> I think all we need is to add `taxonomy_single.html` and `taxonomy_list.html` to the `templates` directory.

This is indeed enough to create the pages.

However, do you expect these taxonomies to be shown in the post metadata? That is, in the actual article, below the title, and in the post listing (blog section)?

Can you tell me a bit more about your intended use case?

Thanks!

**Comment by arichtman** [comment]
Good question, I would like to at least be able to filter posts based on a second taxonomy. Presently I have one for post category, where I track if it's a tutorial, reference document, etc. I don't need the taxonomy to show on the post page or in sections, it's a nice-to-have but I think it would be complicated to generalize for n taxonomies

**Comment by welpo** [comment]
So, if I understand correctly, it would be enough for your needs to only provide the fallback templates?

The listing or individual pages would be orphan links unless you linked them yourself from some place (like the menu or an article).

Is that good enough?

**Comment by arichtman** [comment]
Yes. I only have one other taxonomy so it doesn't bother me to link it  manually.

**Comment by welpo** [comment]
Done!
