### ISSUE TITLE
previos and next link in page

### ISSUE THREAD

**Issue by ziyouwa** [welpo/tabi#244]
On the article page, there is no link to the previous or next article. How to enable it?

**Comment by welpo** [comment]
Hi!

It is not possible right now. Working on it:

![](https://github.com/welpo/tabi/assets/6399341/e393f55e-3e0b-41c5-8aa8-8b40b41c7aee)

**Comment by welpo** [comment]
Added it in #246. See [the docs](https://welpo.github.io/tabi/blog/mastering-tabi-settings/#previous-and-next-article-links).

Use `show_previous_next_article_links = true` in your page, section or `config.toml`.
