### ISSUE TITLE
About multi sources in Archive

### ISSUE THREAD

**Issue by ziyouwa** [welpo/tabi#251]
I'm very sorry for the late reply. 
About [#249](https://github.com/welpo/tabi/pull/249), I created a new site to test this modification, and my steps are as follows: First, I divided the blog directory into blog, blog2, and blog3, and modified the path, title, and social_media_card values in the _index.md files of the latter two. Then I copied the social_card directories blog2 and blog3. Then I modified content/_index.md and changed section_path to section_path = [“blog/”,“blog2/”, “blog3”], but running zola serve will report an error:
Error: Reason: Failed to render 'section.html'
Error: Reason: Function call 'get_section' failed
Error: Reason: get_section requires a path argument with a string value

**Comment by welpo** [comment]
The `section_path` should be changed only for the `content/archive/_index.md` file: https://github.com/welpo/tabi/blob/main/content/archive/_index.md?plain=1

If this still doesn't help, can you create a repository where I can see your setup?

**Comment by ziyouwa** [comment]
It's OK! Thank you very much!

**Comment by ziyouwa** [comment]
2024 was placed before 2023, 2022, and 2021 when archiving. I don't know how to fixed it, pls help me.

**Comment by welpo** [comment]
This is expected. In blog pages, the archive section is typically rendered in a "newest to oldest" order. This design choice aligns with the general user expectation to access the most recent content first. Readers are often more interested in the latest posts, as they tend to be more relevant to current events or recent developments.

**Comment by welpo** [comment]
Would you like a chronological order Archive? That is, oldest to newest posts?

**Comment by ziyouwa** [comment]
Sorry for my english. The order is 2023, 2022, 2021, 2024. 2024 is last.

**Comment by welpo** [comment]
Understood! I've replicated the issue. Fixing it now.

**Comment by welpo** [comment]
Please let me know if the latest commit (2c8a21d558f5f6b3a208a3caf9a88b01c92ca0e1) fixes it.

Thanks for reporting the bug!

**Comment by ziyouwa** [comment]
It's perfect! Thank you very much!
