### ISSUE TITLE
Header anchor in Arabic text is not working

### ISSUE THREAD

**Issue by TheAwiteb** [welpo/tabi#269]
# Bug Report

## Environment
tabi version or commit: e3734829460d4f93643e7d8fc4a33670f5bb9c6e

## Description
There is a bug in the header anchor in Arabic text.

## Steps to reproduce
1. Hover over the header anchor in the Arabic text.

https://github.com/welpo/tabi/assets/59842932/3b72382b-da7c-4c56-ac76-5b46a85285de

**Comment by welpo** [comment]
Did you try setting `insert_anchor_links = "right"` on the section?

You need to set it on the TOML of the section (i.e. `_index.md`).

[Example on the docs](https://welpo.github.io/tabi/blog/mastering-tabi-settings/#projects). Adapted for the blog section (`content/_index.md`):

```
paginate_by = 5
path = "/blog"
title = "Blog"
sort_by = "date"
template = "section.html"
insert_anchor_links = "right"  # ✅ try this 
```

**Comment by TheAwiteb** [comment]
> Did you try setting `insert_anchor_links = "right"` on the section?

I tried it a while ago, and it's set it in the left not right 

![image](https://github.com/welpo/tabi/assets/59842932/5b72596d-64d5-4608-936a-7b4f0036dcd6)

**Comment by TheAwiteb** [comment]
This is the headers if you want to test something (Arabic **ar**)

```text
# موضوع 1

## موضوع 2

### موضوع 3

#### موضوع 4

##### موضوع 5
```

**Comment by welpo** [comment]
I will look into it! Thanks.
