### ISSUE TITLE
Blog and Projects on homepage

### ISSUE THREAD

**Issue by Myrdincx** [welpo/tabi#291]
I'm not sure if this is already possible, but it would be nice:

# Feature Request

## Summary
The ability to display both your latest blog posts as well as the latest projects on the main page.

## Motivation
I guess it would add some variety between your blog posts and latest projects being directly visible on the main page.

## Detailed Description
I'm not quite sure how it would be implemented, but looks-wise, it would be pretty much the same as how blog posts are being displayed at the homepage right now.
Only difference would be that projects don't always have a set date in their config.

Additionally, there could be some way of displaying which one is a blog post and which one is a project.

**Comment by Myrdincx** [comment]
I think a separate section would be quite nice.

**Comment by welpo** [comment]
How about its header?

"Latest projects" feels wrong, as they are sorted by `weight`, not date…

I'm leaning towards something like "Featured projects".

What are your thoughts?

**Comment by Myrdincx** [comment]
"Featured projects" sounds great honestly!

**Comment by welpo** [comment]
Done in #297!

Let me know if you encounter any issues~

**Comment by Myrdincx** [comment]
@welpo There is one small little issue.
When using `show_projects_first = true`, the Latest Posts scoot to the right side, inside of being aligned in the middle as shown in the image:
![image](https://github.com/welpo/tabi/assets/69009601/24fc668c-0fe8-4c37-868c-4fb1c0b351c8)

**Comment by welpo** [comment]
Fixed in 69094d633579a1ea4bee1fcadd77e1511d4020ca
