### ISSUE TITLE
Misaligned posts when showing latest projects

### ISSUE THREAD

**Issue by welpo** [welpo/tabi#300]
@welpo There is one small little issue.
When using `show_projects_first = true`, the Latest Posts scoot to the right side, inside of being aligned in the middle as shown in the image:
![image](https://github.com/welpo/tabi/assets/69009601/24fc668c-0fe8-4c37-868c-4fb1c0b351c8)

Other than that, awesome for adding this, thank you so much!

_Originally posted by @Myrdincx in https://github.com/welpo/tabi/issues/291#issuecomment-2081507666_

**Comment by welpo** [comment]
This only happens with `minify_html = false` on `config.toml`.

**Comment by Myrdincx** [comment]
This is probably a really stupid request, but would it be possible to add a little bit more spacing between the latest posts and the projects?

![image](https://github.com/welpo/tabi/assets/69009601/178cbf69-c982-4d5b-9886-8e0d69e6f52f)

**Comment by welpo** [comment]
> This is probably a really stupid request

Not at all—it's a bug. Fixing it now.

By the way, don't be afraid to create issues for stuff like this; I prefer it. You can ignore the template if it's overwhelming. As long as you explain it clearly, it's fine :)
