### ISSUE TITLE
Projects in RSS Feed

### ISSUE THREAD

**Issue by Myrdincx** [welpo/tabi#302]
# Feature Request/Summary
Ability to show projects in the RSS feed/Atom Feed

## Motivation
The ability to see both posts and projects in the rss feed is a nice little feature :)

**Comment by welpo** [comment]
It's already possible! To do this, you need to add a `date` on the project's front matter. Example:

```md
+++
title = "git-sumi"
description = "The non-opinionated Rust-based commit message linter."
weight = 10
date = 2022-02-02
+++
```

**Comment by Myrdincx** [comment]
Is there a way for them to show up in the feed, without having the little text under the title?
![image](https://github.com/welpo/tabi/assets/69009601/54c1ca58-642c-4571-a001-c06fc4afdabe)

**Comment by welpo** [comment]
Not yet. All add the option soon.

**Comment by welpo** [comment]
Try updating tabi and setting `show_date = false` on your page/entire projects index :)
