### ISSUE TITLE
E-mail icon dissapears when all social icons are off

### ISSUE THREAD

**Issue by stalkerGH** [welpo/tabi#312]
I'd like to turn off all social icons (yes, all of them) and have only e-mail active. But if I comment off entire social section or separate social icons, e-mail icon dissapears too. If I let only one social icon be turned on (any of them), e-mail icon is visible and active. How can I fix it?

**Comment by welpo** [comment]
That was a bug. Thanks for letting me know.

I fixed it in aef49bb.

If you update tabi, you should be able to only show the email/feed icons without any other socials.
