### ISSUE TITLE
Add OSM map (Leaflet) to Tabi

### ISSUE THREAD

**Issue by stalkerGH** [welpo/tabi#313]
I'd like to add Openstreetmap maps to my blog post, preferably in Leaflet library. I have done it in "normal" HTML but I don't know how to do it in Zola and Tabi. Maybe it is built-in Zola's feature but I don't know how to call it.

**Comment by welpo** [comment]
You can add HTML directly on your posts, and it'll be rendered normally. Have you tried that?

One issue you might encounter is related to CSP: you might need to allow the OpenStreetMap connection or disable CSP.

**Comment by stalkerGH** [comment]
Thank you. I added IFRAME code generated by OSM.org and the frame was visible but no content. I added OSM to CSP rules and it works now. Thank you!

**Comment by stalkerGH** [comment]
My problem is solved so I close the issue.

**Comment by welpo** [comment]
No problem! Glad to hear you solved it :)
