### ISSUE TITLE
author in page.html

### ISSUE THREAD

**Issue by faassen** [welpo/tabi#319]
# Feature Request

Author information on blog posts.

## Summary

Optionally include author information on individual pages.

## Motivation

I realize this information can be on the home page, about page and in the copyright footer, but I like it to be immediately obvious when you click through to my blog post that I wrote it, without having to scroll or follow links. Interestingly atom feeds already include this information.

## Detailed Description

I'd like my blog post to include the author name before the date and tags, or under the title somehow. The author can be taken from the config, though could be overridden by page authors. There can be a global toggle to turn this on.

**Comment by welpo** [comment]
Alright, the code is ready, but I need to:

- Write the docs
- Decide on the format

I'm leaning towards using the author as is, without prefixes. I'm open to suggestions, though.

**Comment by faassen** [comment]
That's what I have done in my template hack, just put in the author name. Like this:

```
Martijn Faassen  •  2024-05-24  • Tags: ..
```

You could prefix it with `Author: ` too, which would make it consistent with `Tags`. That would make it clear my name is a name and not some weird language you can't read.

I noticed that config has a single author but pages can have specific multiple authors too. I haven't dealt with the latter as this is a personal blog, but that may be something to keep in mind.

**Comment by welpo** [comment]
> I noticed that config has a single author but pages can have specific multiple authors too. I haven't dealt with the latter as this is a personal blog, but that may be something to keep in mind.

Thank you! I had not considered it.

> That would make it clear my name is a name and not some weird language you can't read.

I also had not considered certain names might be confusing without any context. I decided to go with `By $AUTHOR`, as "Author: $AUTHOR" would be problematic for languages with grammatical gender.

**Comment by welpo** [comment]
Done! Let me know if you encounter any issues~
