### ISSUE TITLE
<h2> renders (almost?) the same size as <h1>

### ISSUE THREAD

**Issue by faassen** [welpo/tabi#321]
# Bug Report

When I have a document which uses `##` headings to go one level deeper, it renders like a `#`.

## Environment

Zola version: 0.18.0
tabi version or commit: c54251ca7ab6f715ceacba7ed6406df683aa364b

## Expected Behavior

I expect `##` (h2) headings to be rendered smaller than `h1` headings.

## Current Behavior

On desktop firefox at least the rendering is so close in size I can't really distinguish between them.

## Step to Reproduce

Use `#` and `##` headings in a document.

**Comment by welpo** [comment]
You're right, they're very close in size. I'll increase the size of h1 a bit.

Side note: it's generally recommended to use only one h1 per page, and the post's title is already h1.

**Comment by faassen** [comment]
Yeah, I'm converting hundreds of old blog entries and I may have to go through them all to increase the nesting level in the places where that's lacking.
