### ISSUE TITLE
Possible performance issues

### ISSUE THREAD

**Issue by faassen** [welpo/tabi#324]
# Bug Report

I am getting a slow performance generating my blog, detailed here:

https://github.com/getzola/zola/issues/2508

It's possible Tabi plays a part here so I hope you don't mind I pull you in.

Do you have any idea what in the page or atom template could be causing slowness?

I have gone live with my zola and tabi based blog yesterday by the way, thanks for all your help! I like it:

https://blog.startifact.com

**Comment by faassen** [comment]
I've done some experimenting, and if I stop using the `evaluate_setting_priority` macro the build time goes from 8+ seconds on my laptop to under 1 second. I'm not sure *why* this happens, but it's pretty drastic.

**Comment by faassen** [comment]
Thanks to the zola devs, this change speeds up the build times massively. It takes less than 700 ms now on the same machine.  In `evaluate_setting_priority` change:

` {%- set current_section = get_section(path=last_ancestor.0) %}`

to:

`{%- set current_section = get_section(path=last_ancestor.0, metadata_only=true) %}`

**Comment by welpo** [comment]
Thank you so much! Sorry I didn't have time to check this earlier, but I'm really happy you managed to solve it! Merging the PR now.
