### ISSUE TITLE
Show "updated date" instead of creation date

### ISSUE THREAD

**Issue by sam9032** [welpo/tabi#326]
# Show "updated date" instead of creation date

Hi there,

thank you for the amazing theme. It looks beautiful and works well!
I just started with my own [website and blog](https://sam-peters.de).

## Summary

Is there a way to display the "Last updated" date instead of the creation date on the start-page, atom-page and blog-page?

## Motivation

I want to add new things to my posts over time. If its just an addition to an existing topic I don't want to create a new blog post.
Right now the change is only visible to a website visitor if he opens the post and sees the "Last updated".

**Comment by welpo** [comment]
Hey Sam!

Thanks for the kind words~

Currently there's no way to add the last updated date. It wouldn't be too hard to add, though. Do you picture it below the creation date? Or showing one instead of the other?

**Comment by sam9032** [comment]
Hm, good question... I'm just fiddling with it and have replaced it for now.
But making it similar to the view under the blog title on the blog page might be good too? :smile: 

Right now I've set my own entry in the `config.toml`: `prefer_updated_date`  
and use it in the `list_posts.html` macro:

![](https://github.com/welpo/tabi/assets/12381166/36b521f0-511b-4ea4-80b6-f31d445618fc)

**Comment by welpo** [comment]
I'm thinking we could add a variable `post_listing_date_shown` (or another descriptive name) with three options:

- `date`
- `update` (or `updated`?)
- `both`

The logic to show either/both should be easy to implement.

Thoughts?

**Comment by sam9032** [comment]
I think that's a good idea. That way, everyone can decide for themselves what they want.

**Comment by welpo** [comment]
Great!

Would you like to work on this? It needn't be a complete PR, but anything helps!

**Comment by sam9032** [comment]
Yes, I'll give it a try!

*Von: *Óscar ***@***.***>
*An: *welpo/tabi ***@***.***>
*Kopie: *sam ***@***.***>; Author ***@***.***>
*Datum: *12.06.2024 01:21:30
*Betreff: *Re: [welpo/tabi] Show "updated date" instead of creation date (Issue #326)

**Comment by welpo** [comment]
Awesome! Don't hesitate to reach out with questions or to create a semi-complete PR~

**Comment by welpo** [comment]
Added in #330.
