### ISSUE TITLE
Add language support for search engine

### ISSUE THREAD

**Issue by stalkerGH** [welpo/tabi#329]
I'm trying to add search engine to my website. Unfortunately, it seems that my language is not supported by Zola & tabi:

```
Error: Failed to serve the site
Error: Tried to build search index for language pl which is not supported
``` 

Or maybe I should ask Elasticlunr developers...?

**Comment by welpo** [comment]
I believe Zola uses `elasticlunr-rs`. Related discussion: https://github.com/mattico/elasticlunr-rs/issues/13

If elasticlunr supports it and Zola is updated to use the last elasticlunr, tabi will work with its search index (with no changes).

**Comment by stalkerGH** [comment]
OK, I don't see support for my language. I have to investigate it.
