### ISSUE TITLE
Icons for "info" and "note" admonitions should be the other way around

### ISSUE THREAD

**Issue by grifferz** [welpo/tabi#337]
# Bug Report

## Environment

Zola version: 0.19.0
tabi version or commit: HEAD

## Expected Behavior
I would expect "Info" admonitions to have an icon that resembles an 'i' and "Note" admonitions to have one that is more striking.

## Current Behavior
Currently "Info" admonitions have an icon that resembles an exclamation mark in a circle, while "Note" admonitions have one that resembles an 'i'. This just seems backwards because it makes the "Info" icon more alarming than the "Note" icon.

## Step to Reproduce
The current icon appearance can be seen on  the documentation for admonitions at https://welpo.github.io/tabi/blog/shortcodes/#admonitions

I appreciate this may be a matter of taste although it seems correct to me that these icons should just be switched. For now I have overridden this in my CSS.

**Comment by welpo** [comment]
The design is based off Docusaurus: https://docusaurus.io/docs/markdown-features/admonitions

I'd be happy to reconsider other specific icons, though.

**Comment by welpo** [comment]
Some notes might be more important than others. I opted for adding the parameter `icon` to the admonition shortcode in #340.

Hope that helps! :)

**Comment by grifferz** [comment]
I still don't think it makes sense that the default icon for info is a '!' while the default icon for note is an 'i', but I will take that up with the Docusaurus repo.

Your addition of the `icon` parameter does allow me to fix that without overriding anything, so thank you!
