### ISSUE TITLE
Feat: make tubi work with Zola 0.19

### ISSUE THREAD

**Issue by gacallea** [welpo/tabi#338]
# Feature Request

## Summary
Zola 0.19.0 is out and there are breaking changes. It would be nice if tabi would update the code to work with it.

## Motivation
If I could I'd stick with Zola 0.18 indefinitely but this would benefit everyone.

## Detailed Description
Some examples where things break:

- `generate_feed` becomea `generate_feeds`
- `path` becomes `paginate_path`

## Additional Context
After the above running `zola serve` gives:

```
╰─❯ zola serve
Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 1 pages (0 orphan) and 6 sections
Error: Failed to serve the site
Error: Failed to render section '/Users/andreacfromtheapp/Sites/gacallea.github.io/content/sound/_index.md'
Error: Reason: Failed to render 'cards.html'
Error: Reason: Function call 'get_url' failed
Error: Reason: Variable `config.feed_filename` not found in context while rendering 'partials/footer.html'
```

Who knows what else breaks after that (not a criticism, it is a major update on Zola behalf).

Please and thank you

**Comment by welpo** [comment]
Hi!

Are you using the latest tabi commit? The footer issue should be fixed with #336

**Comment by gacallea** [comment]
> Hi!
> 
> Are you using the latest tabi commit? The footer issue should be fixed with #336

Hi!

not sure, I ran `git submodule update --recursive` as well but nothing was fetched.

**Comment by gacallea** [comment]
```
╰─❯ git submodule update --recursive
╰─❯ cd themes/tabi/
╰─❯ git status
HEAD detached at 5ae629d
nothing to commit, working tree clean
```

**Comment by welpo** [comment]
Try:

```bash
cd themes/tabi/
git fetch origin
git checkout main
git pull
```

**Comment by gacallea** [comment]
thanks!

**Comment by welpo** [comment]
Sorry about the wrong docs regarding updates! Will fix now.
