### ISSUE TITLE
Archives template: years ordered descending but posts not ordered at all

### ISSUE THREAD

**Issue by metaleap** [welpo/tabi#339]
Thanks for a fine theme! But, any ideas on this? Unexpectedly, my listing based on `archive.html` template has its year-sections ordered fine **but** posts in _every_ year-section unordered, such as here:

![image](https://github.com/welpo/tabi/assets/22109/3133f1b0-d08e-4979-86a9-5263fafe05a0)

But the `.md` files in question do have proper `date`s:

![image](https://github.com/welpo/tabi/assets/22109/f0d888d4-73dc-493d-871f-b16ab02c5689)

And `content/blog/_index.md` is just simply:

```
+++
title = "Posts"
template = "archive.html"
+++
```

This is with v2.11.0 (just `git clone`d yesterday).

**Comment by metaleap** [comment]
Thaaat's it, thanks for that! Wasn't on my radar — it's the `blog` section itself that is directly using the `archives.html` template, no separate `archives` section here. But this solves the issue here, merci!

**Comment by welpo** [comment]
Great! I'll add a mention of this to the docs.
