### ISSUE TITLE
Feature suggestion: sort-order setting for Tags listing page

### ISSUE THREAD

**Issue by metaleap** [welpo/tabi#341]
For some sites, it would be desirable if a tags listing page such as [this](https://welpo.github.io/tabi/tags/) could be set to sort the tags not alphabetically but by number-of-items (descending). This brings the "most focused-on topics on this site" right to the top, with the "less-relevant / misc / side show topics" right at the bottom.

**Comment by welpo** [comment]
Makes sense! We would need to modify [`taxonomy_list.html`](https://github.com/welpo/tabi/blob/main/templates/taxonomy_list.html).

I'm thinking a variable like `tag_sorting` with two options: `name` or `frequency`.

Would you be interested in creating a PR?

**Comment by metaleap** [comment]
Well alright I'm gonna give it a shot, stay tuned

**Comment by welpo** [comment]
Great! Don't hesitate to reach out or open an incomplete PR. I'll happily assist wherever possible.

**Comment by metaleap** [comment]
Eh, I don't get it. Even just changing `{%- for term in terms -%}` to `{%- for term in terms | reverse -%} or `{%- for term in terms | reverse() -%} doesn't change the sorting. Even after hard-restarting `zola serve`.

Of course reverse-alphabetical wouldn't be the _final desired_ sorting, but this was just a first attempt and already a total lack of visible result is laughing in my face. Gonna postpone learning yet-another-many-paged-friggin-documentation-big-book, this time for "the Tera language", until ... whenever.

**Comment by welpo** [comment]
My bad!

Your code is correct. I linked **one of** the files that need modifying. The template that handles tags is: https://github.com/welpo/tabi/blob/main/templates/tags/list.html

Sorry~

**Comment by metaleap** [comment]
Thank you! Got it working, PR incoming.
