### ISSUE TITLE
Suggestion: singularize count-per-tag (in Tags listings) to read "1 post" instead of "1 posts"

### ISSUE THREAD

**Issue by metaleap** [welpo/tabi#349]
The basic idea: see title  =)

To clarify the current situation:

![image](https://github.com/welpo/tabi/assets/22109/37a8183a-b10e-423c-99a5-2fc3c21c62d6)

**Comment by welpo** [comment]
Is this the /tags/ page? It works on the demo: https://welpo.github.io/tabi/tags/

**Comment by metaleap** [comment]
Yes it is! That's so odd, has this been a _very recent_ fix? I think my tabi copy is from about half a week, less than a week ago..

And with custom skin but that's just scss, hardly matters.

Anything missing in the below, per chance?

```
taxonomies = [{ name = "tags", feed = false }]

(....)

menu = [
    { name = "Blog", url = "blog", trailing_slash = true },
    { name = "Topics", url = "tags", trailing_slash = true },
    { name = "CV", url = "cv", trailing_slash = true },
]
```

**Comment by welpo** [comment]
> has this been a _very recent_ fix?

Nope. The current pluralisation method was added with #277, four months ago.

- Have you modified anything in terms of i18n?
- What's the `default_language` in `config.toml`?

**Comment by metaleap** [comment]
Oh, interesting pointer. I do have a custom `./i18n/en.toml` with a single line `all_tags = "Blog post tags:"`. And guess what — when I disable it (renaming folder temporarily), the "1 post" show up correctly...

**Comment by welpo** [comment]
As per [the docs](https://welpo.github.io/tabi/blog/faq-languages/#how-do-i-customise-or-override-a-specific-text-string-on-my-website), you should copy the entire file and then customise it. I know it's not ideal, but there's no better way to do this right now.

If you copy the entire file and add/replace a string, everything should work as expected. The caveat is that future tabi updates which change i18n will require you to update the i18n files (or rely on the fallback strings, which work except for pluralisation).

**Comment by metaleap** [comment]
Oh crikey, guess I missed that part! Thanks... would really be preferable if these toml file overrides would be merged on the fly, but I guess that's a Zola thing not a Tabi thing. Merci then!

**Comment by welpo** [comment]
Yeah, it's unfortunate. The current i18n setup is a huge hack and not how translations are supposed to work, but it's much better than the default setup.
