### ISSUE TITLE
OpenGraph tags?

### ISSUE THREAD

**Issue by arichtman** [welpo/tabi#353]
# Feature Request

## Summary

Adding OpenGraph tags to header and as optional config

## Motivation

Links to pages show a more customized and richer preview card.

## Detailed Description

I think it's just some short code in the header to interpolate the configuration items.

## Additional Context

Specification: https://ogp.me/

Here's some themes that do it: https://www.google.com/search?client=firefox-b-d&q=site%3Agetzola.org+opengraph

Here's a comment saying it belongs in the theme: https://zola.discourse.group/t/idea-better-page-metadata-for-published-pages/111/2

(I wouldn't have minded if it was supported better in core Zola tbh)

I can take a crack at it - mostly checking if there's any interest.

Sample

![image](https://github.com/welpo/tabi/assets/10679234/317cfe06-b6e8-4891-a01c-5d02d6998023)

**Comment by welpo** [comment]
Hi!

The [header template](https://github.com/welpo/tabi/blob/main/templates/partials/header.html) includes a bunch of og tags (search for `og:`).

What tags are you missing?

**Comment by arichtman** [comment]
Oh whoops! I'm blind. Sorry and thanks for your time!

**Comment by welpo** [comment]
No worries! Appreciate the intent~

**Comment by welpo** [comment]
[Added](https://github.com/welpo/tabi/commit/fbb81f976433d93ee3787f4a9d5c6c3049f815a2) a mention of the feature on the README :)
