### ISSUE TITLE
bug: feed not working (anymore?)

### ISSUE THREAD

**Issue by gacallea** [welpo/tabi#361]
# Bug Report

## Environment

Zola version: zola 0.19.1
tabi version or commit: 82f7a98

## Expected Behavior

I have set both `generate_feeds = true` and  `feed_filenames = ["atom.xml"]` and I would expect feeds to work out of the box.

I also have `taxonomies = [{ name = "tags", feed = true }]` if this matters at all.

## Current Behavior

Atom feed should work but it doesn't. The weird thing is that it does work locally (zola serve).

**Comment by gacallea** [comment]
site: https://gacallea.github.io
source: https://github.com/gacallea/gacallea.github.io

**Comment by welpo** [comment]
Hi!

Your local Zola is 0.19.1, but you're building with 0.18.0: https://github.com/gacallea/gacallea.github.io/blob/da276e26bbef6b89d1cb3356d5298899466db775/.github/workflows/main.yml#L13C1-L13C48

Zola 0.18.0 can't read the new configuration options.

Change that line to:

```
        uses: shalzz/zola-deploy-action@v0.19.1
```

and it should work :)

**Comment by gacallea** [comment]
oopsie...

thanks buddy, I have updated it and I trust it will work
