### ISSUE TITLE
Content of `h2` elements overlaps when wrapping on multiple lines

### ISSUE THREAD

**Issue by DataTriny** [welpo/tabi#374]
# Bug Report

## Environment

Zola version: 0.19.2
tabi version or commit: ce3be5c007fa23bfa6ebb09b3fcab9e2ad9f06fa

## Expected Behavior
The content of `<h2>` elements should be readable even when it spans multiple lines, characters from different lines should not overlap.

## Current Behavior
Characters vertically overlap as can be seen in the screenshot below:

![Screenshot of the home page of accesskit.dev on mobile](https://github.com/user-attachments/assets/af7676d3-5479-45aa-b585-62807bb7ee42)

## Step to Reproduce
Go to [accesskit.dev](https://accesskit.dev), either on mobile or resize the browser window so that the text "Accessibility infrastructure for UI toolkits" can't fit on a single line.

**Comment by welpo** [comment]
Thank you for reporting this!

It should be fixed with #375. The PR reduces the font size of headers and lists in the home banner to match the sizing in articles, effectively fixing the issue.
