### ISSUE TITLE
Multiple Languages Messages in 404 page

### ISSUE THREAD

**Issue by soumendrak** [welpo/tabi#377]
# Bug Report

## Environment

Zola version: latest
tabi version or commit: latest

## Expected Behavior
The selected language should be the language in which the 404 error message should be displayed on the website.

## Current Behavior
The 404 message is displayed across all the enabled languages.

## Step to Reproduce
1. Go to https://welpo.github.io/tabi/notexist

![image](https://github.com/user-attachments/assets/30e7334c-62c6-4e70-bea0-1d4605c09941)

**Comment by welpo** [comment]
It would be nice to serve the right 404 based on the language. If you think about it, though, how can a static site know what the intended language was?

In short: it's a Zola limitation (see https://github.com/getzola/zola/issues/821#issuecomment-545115965) which I'm not sure how it could be technically solved (other the rather dirty "create various 404s, use JS/cookies to redirect").

I decided to offer multi-language support for 404 with messages in all languages as a compromise.

**Comment by welpo** [comment]
That's not something you can do with Zola; that's something the webserver (nginx, apache…) would do. The default behaviour is "redirect missing pages to `404.html`". See this nginx example: https://stackoverflow.com/a/43392815
