### ISSUE TITLE
skins don't work as intended when OS theme is set to dark

### ISSUE THREAD

**Issue by welpo** [welpo/tabi#379]
Reported in #378. Most likely the bug was introduced in #357.

To reproduce:

0. Set OS theme to dark
1. Clone `https://github.com/welpo/tabi.git`
2. Set `skin = "red"` in config.toml
3. Run `zola serve --open` at the root of clone.

![image](https://github.com/user-attachments/assets/07c71805-20ad-4b9c-9f5b-5cbcd41a1770)

_Originally posted by @JVimes in https://github.com/welpo/tabi/discussions/378#discussioncomment-10629053_

**Comment by welpo** [comment]
Confirmed it was introduced with #357.

[This line](https://github.com/welpo/tabi/blob/1b11f4b321d0ae52179d88cc3ecd1b72ef2b37ae/sass/main.scss#L119) causes the issue. Using adding `!important` to skin variables serves as a workaround.

**Comment by welpo** [comment]
@JVimes should be fixed with #380. Let me know if you encounter any issues!

Thanks for reporting this and for using tabi~

**Comment by JVimes** [comment]
Worked for me! Thank you, @welpo!
