### ISSUE TITLE
Document the nested pages

### ISSUE THREAD

**Issue by TheAwiteb** [welpo/tabi#386]
I actually lost after #385 PR to figure out how nested pages works.

After I figured out how it works it makes sense, but I don't think it does for newcomers.

I think if it is added to the "Features" section in the README and a simple topic about it explaining how to create it and where it will be and that it will not be found in the posts, that would be good.

@welpo What do you think?

**Comment by welpo** [comment]
Nested pages aren't a tabi-specific feature. All themes should be able to render them (unless they had a bug like tabi had hehe).

I prefer to keep the tabi docs tabi-centered. A general explanation of nested pages belongs to the Zola docs, in my opinion.

That said, I couldn't find much official information from the Zola docs. Either the (Zola) docs need to be improved, or it's assumed it's obvious.

What do you think?

**Comment by TheAwiteb** [comment]
I was thinking about document it, but it's look likes it mentioned [here][1] but not directly. I think it just takes focus to know that it works.

[1]: https://www.getzola.org/documentation/content/page/#path-from-filename

**Comment by welpo** [comment]
Agreed. It was confusing for me too.
