### ISSUE TITLE
Support for relative paths and line ranges in remote_text shortcode

### ISSUE THREAD

**Issue by apirogov** [welpo/tabi#397]
# Feature Request

## Summary

The `remote_text` shortcode is insanely useful, because I prefer having a source file with code and not copy it into the markdown. However, I did not find a way to use the shortcode with a relative path, I have to use it like

<pre>
```python
{{ remote_text(src="/content/blog/article_name/code_file.py") }}
```
</pre>

Instead, I would like to be able to write

<pre>
```python
{{ remote_text(src="code_file.py") }}
```
</pre>

Ideally I could do something like:

<pre>
```python
{{ remote_text(src="../../some_location/code_file.py" start=10 end=20) }}
```
</pre>

as is supported (with some pretty weird syntax) by e.g. [pymdown.extensions](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#snippet-lines) for mkdocs.

## Motivation

The relative path feature would make renaming the article/its directory much easier and less error-prone. I tend to colocate the source files with more complex articles, and I tend to rename the article multiple times before its done (I follow a `YYYY-MM-DD-article-name-slug` directory naming scheme to have a chronological order, and I often need to e.g. fix up the date).

The line range feature would be super useful both for reusing text sections on different pages, or to have different parts of the source file added in an article with paragraphs of text in between with explanations etc.

----

Unrelated to the issue, just wanted to say thanks for creating this awesome template! In the recent updates tabi and zola got all the features that I had to hack in before with a bunch of workarounds and copy-pasted snippets, but recently I updated to the most recent version and was happy to see that I do not need any custom hacks anymore, everything is configurable to my needs without much effort :)

**Comment by welpo** [comment]
Hey @apirogov!

I've added support for relative paths in #398 and support for line ranges in #399. Let me know if you encounter any issues!

---

Thanks for the kind words. I'm happy to hear tabi works for you~

In the future, feel free to share your hacks as PRs or feature requests! Even if incomplete; I'm sure we could make use of them.

**Comment by apirogov** [comment]
Perfect, thanks a lot! :)
