### ISSUE TITLE
Fediverse authorship tag

### ISSUE THREAD

**Issue by arichtman** [welpo/tabi#408]
# Feature Request

## Summary

The Fediverse is a decentralised social web.
The de facto implementation for microblogging is Mastodon.
Mastodon 4.3 adds support for a meta tag that allows better attribution and cross-site accessibility for bloggers and authors.

## Motivation

Allows better integration and access between sites using Tabi and Fediverse creators.

## Detailed Description

Add a conditional to the header template that inserts the required meta element.

## Additional Context

https://blog.joinmastodon.org/2024/10/mastodon-4.3/

https://rknight.me/blog/setting-up-mastodon-author-tags/
https://orbitalmayo.net/posts/include-fedi-profile-link-previews/

**Comment by welpo** [comment]
Implemented in #409
