### ISSUE TITLE
Add the ability to make codeblocks ltr in rtl languages

### ISSUE THREAD

**Issue by mohammad-amin-khajeh** [welpo/tabi#411]
# Feature Request

## Summary
Making codeblocks more sane and correct behaving. There's no need for them to ever be rtl in my opinion.

## Motivation
Comments in a codeblock may or may not be in the rtl language at hand, however there is no need for the code itself to be rtl, in fact it looks very wrong and weird most of the times.

## Detailed Description
I suggest adding `code,pre {direction: ltr}` to `sass/parts/_code.scss` or at least adding a shortcode that adds such feature

### Code editor(ltr)
![2024-10-15 23-16-52](https://github.com/user-attachments/assets/6118e23f-1732-4cc7-89c9-14a64390111c)
### Website(rtl)
![2024-10-15 23-17-03](https://github.com/user-attachments/assets/37dbf872-09bd-4556-b908-2193941fb11d)

**Comment by welpo** [comment]
Makes sense to me.

Would the header (colour bar) be okay as is?

**Comment by mohammad-amin-khajeh** [comment]
Yes actually the header is just fine as it is. It's just the alignment of code below it that is quite irritating.
