### ISSUE TITLE
Sidebar shortcode

### ISSUE THREAD

**Issue by welpo** [welpo/tabi#444]
### Summary and motivation

I like the idea of sidenotes/sidebars; sitting somewhere between a proper paragraph and a footnote.

On desktop (or a big tablet), there's plenty space on the left/right margins to add this feature.

It could look like:

![desktop](https://github.com/user-attachments/assets/48cf581d-94ce-4635-8afe-6e8ff6927732)

on mobile:

![mobile](https://github.com/user-attachments/assets/65aea6c4-fb30-4ab7-92e1-24b8d2541159)

Live: https://diataxis.fr/

### Implementation details

Diataxis uses font size 90%.

### Checklist

- [X] I've searched existing issues to make sure this feature hasn't already been requested.
- [X] This feature aligns with tabi's philosophy (minimal JS, accessible…)
- [X] I'm willing to contribute to the implementation of this feature.

**Comment by stalkerGH** [comment]
I like the idea!

**Comment by welpo** [comment]
Something to consider: adding footnotes as sidenotes:

![lw](https://github.com/user-attachments/assets/4620cb3b-4418-46d0-881e-41273e1ba0a5)

https://www.lesswrong.com/posts/dLg7CyeTE4pqbbcnp/language-models-model-us

For desktop: notes are shown in two places: right next to the mention + at the end.

On mobile, they are only shown at the end.
