### ISSUE TITLE
Images as links

### ISSUE THREAD

**Issue by stalkerGH** [welpo/tabi#445]
### Summary and motivation

I'd like to use image as link - no additional text, just image. Click on it and be moved to the webpage. Is it possible or could be?

### Checklist

- [X] I've searched existing issues to make sure this feature hasn't already been requested.
- [X] This feature aligns with tabi's philosophy (minimal JS, accessible…)
- [ ] I'm willing to contribute to the implementation of this feature.

**Comment by welpo** [comment]
Yeah, you can use HTML. I do it in some projects like the [Streaming Royalties Calculator](https://welpo.github.io/tabi/projects/streaming-royalties-calculator/):

```md
<a href="https://osc.garden/royalties-calculator/" target="_blank">
    {{ dual_theme_image(light_src="https://cdn.jsdelivr.net/gh/welpo/osc.garden@main/content/blog/data-analysis-music-streaming/img/calculator_light.webp", dark_src="https://cdn.jsdelivr.net/gh/welpo/osc.garden@main/content/blog/data-analysis-music-streaming/img/calculator_dark.webp" alt="Streaming Royalties Calculator") }}
</a>
```

**Comment by stalkerGH** [comment]
Great, this is exactly I'm looking for! Thank you :)
