### ISSUE TITLE
Dark theme flashes on page load/reload

### ISSUE THREAD

**Issue by eugenesvk** [welpo/tabi#76]
If I manually select the dark theme, I notice that sometimes on page reopen or reload the page flashes - it shows the dark theme for a brief moment and then switches back to black
Is there a way to avoid it?

**Comment by welpo** [comment]
Thanks for reporting this. I'm looking into a fix.

**Comment by eugenesvk** [comment]
From some limited testing I think abridge theme doesn't suffer from this (ssiyad's boring theme also flashes), might be worth looking into how it achieves that

**Comment by welpo** [comment]
It should be fixed now. I had to split the JavaScript logic in two files: one to set the theme (loaded in header), and one with the logic to switch the theme (deferred loading).

Inspiration for the fix: codeandmedia/zola_docsascode_theme@9485c9e30ebe80dc7072ba0f106ccf8909a2dcc7

Thanks again for the report.
