### ISSUE TITLE
Quickstart steps not working (Incompatible units: 'vmin' and 'px')

### ISSUE THREAD

**Issue by wischi-chr** [welpo/tabi#81]
I followed the steps from the README:

```
git clone https://github.com/welpo/tabi.git
cd tabi
zola serve
```

and got the following output / error message:

```
$> zola serve
Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 30 pages (0 orphan) and 11 sections
Error: Failed to serve the site
Error: Internal Error: Incompatible units: 'vmin' and 'px'.
```

I'm currently on commit 58d0dd6f2f918cc0ce8eb649d521d8a385e94bd0 using zola version `0.16.1`

**Comment by welpo** [comment]
Thank you for reporting this.

tabi actually requires Zola version `0.17.0` (I've just updated the docs). You should have no problems if you upgrade.

If that's not an option, you can modify this line:

https://github.com/welpo/tabi/blob/a0f4f4a6420927bb10119baf5327da4c9cf71187/sass/main.scss#L197

To something like:

```css
    margin-bottom: 2.3vmin;
```

(The reason we use `max(2.3vmin, 24px)` is to ensure the margin is always at least 24px but scales up for larger viewport sizes)

**Comment by wischi-chr** [comment]
👍 thank you for the quick response. I installed zola via chocolatey and didn't notice there was a version `0.17`
