### ISSUE TITLE
Style Atom feed

### ISSUE THREAD

**Issue by welpo** [welpo/tabi#83]
Customise the [default template](https://github.com/getzola/zola/blob/master/components/templates/src/builtins/atom.xml) and add an XSL file.

Reference: https://darekkay.com/blog/rss-styling/

Also, modify the template so it doesn't have the full article content. Perhaps just the title and the summary.

**Comment by Jieiku** [comment]
Is this live now? I clicked on the RSS icon in the footer but takes me to this page:

![2023-06-26_15-07-58](https://github.com/welpo/tabi/assets/106644/8003334e-6f58-4814-9486-17aaf452944d)

**Comment by welpo** [comment]
You were a little too quick! It was working locally, but the css and xls paths were incorrect for the github pages setup.

The last two commits (https://github.com/welpo/tabi/commit/a6dfd4d1ba5e781b4d26047a37f925e307de0e6c and https://github.com/welpo/tabi/commit/19bebde14819d8285e50e7ec3cdd1045c66de2a4) should've fixed the issue.

**Comment by Jieiku** [comment]
I seem to only have the problem in Firefox:

![2023-06-26_15-12-50](https://github.com/welpo/tabi/assets/106644/da6aca4d-1626-48dc-8f49-7940845eb98b)

I have tried ctrl+F5 to clear cache
also tried ctrl+shift+p for a private instance which is definitely clean cache

**Comment by welpo** [comment]
Interesting.

It works fine for me on Firefox 114.0.2 (macOS and Windows).

Could you let me know if these stylized feeds work for you?

- https://darekkay.com/atom.xml
- https://photos.darekkay.com/atom.xml
- https://daverupert.com/atom.xml
- https://chrismorgan.info/feed.xml

**Comment by Jieiku** [comment]
Ah HAH! you nailed it!

it was umatrix blocking the request (similar to the noscript browser extension):

![2023-06-26_15-23-07](https://github.com/welpo/tabi/assets/106644/ac20246a-0a53-4d7a-b7d4-b174189ce6b7)

**Comment by welpo** [comment]
Glad to have figured it out!

Thanks for reporting it, it's good to know this can happen to some users (even if they're not many).
