### ISSUE TITLE
Add copy button to code blocks

### ISSUE THREAD

**Issue by welpo** [welpo/tabi#86]
Enabled in `config.toml`. If unset, no JS will be loaded.

**Comment by Jieiku** [comment]
Excellent work on the code blocks! I could see some similarities with the one I used but your js accomplished the same thing in a lot less lines, I also like what you did with the header of the code blocks.

I pulled most of these changes into abridge: https://github.com/Jieiku/abridge/commit/bc671dc40827f65b25d35fa9546181ad4e0f1456
