### ISSUE TITLE
Repeat link

### ISSUE THREAD

**Issue by zhang-wenchao** [welpo/tabi#99]
127.0.0.1:1111/http://127.0.0.1:1111/blog/

**Comment by welpo** [comment]
Hi.

Can you clarify where you are seeing this issue? Is it in the navigation bar (top right)?

**Comment by welpo** [comment]
I believe I've identified the issue. It appears to be related to the way your menu is set up in your `config.toml` file.

Currently, it may be configured like this:

```toml
menu = [
    { name = "blog", url = "$BASE_URL/blog" },
    { name = "archive", url = "$BASE_URL/archive" },
    { name = "tags", url = "$BASE_URL/tags" },
    { name = "projects", url = "$BASE_URL/projects" },
]
```

To fix the issue, remove the `$BASE_URL` part from the URLs, like so:

```toml
menu = [
    { name = "blog", url = "blog" },
    { name = "archive", url = "archive" },
    { name = "tags", url = "tags" },
    { name = "projects", url = "projects" },
]
```

This change was implemented to add multi-language support (commit https://github.com/welpo/tabi/commit/fa9229377d03f229b4deb68bad7cf63b2f88f9fe).

To prevent any similar confusion in the future, I will remove the `$BASE_URL` transformation.

In the future, to make the process as smooth as possible, please use the [bug report issue template](https://github.com/welpo/tabi/issues/new?&template=bug_report.md). It's there to guide you in providing all the information needed to assist you swiftly. 

If you have any other questions or concerns, please don't hesitate to reach out. Thanks for your report, and I appreciate your support for the project! 🚀

**Comment by zhang-wenchao** [comment]
thinks.
